---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages for Communication
    package:
      name: 
        - viber
        - caprine
        - skypeforlinux-stable-bin
        - signal
        - whatsapp-for-linux
        - whatsapp-web-jak

  - name: install packages for Entertainment
    package:
      name: 
        - gimp
        - vlc
        - xine-lib
        - xine-ui
        - mpv

  - name: install packages for system
    package:
      name: 
        - htop
        - tmux
        - dconf-editor
        - keepassxc
        - imagewriter

  - name: install packages for programming
    package:
      name: 
        - go
        - nodejs
        - npm
        - mongodb-bin
        - ruby
        - python
        - stack
        - spring-boot-cli
        - spring-tool-suite

  - name: install packages for tools
    package:
      name: 
        - visual-studio-code-bin
        - virtualbox
        - virtualbox-guest-utils
        - mongodb-compass
        - robo3t-bin
        - zeal
        - docker

  - name: pull images in Docker
    docker_image:
      name: sebp/elk

  - name: install gem rails
    gem:
      name: 
        - rails
        - bundler
      state: latest    
